package com.Ap.HollowKnight.controller.events;

public enum GameEvent {
    BOSS_DEFEATED,
    ENEMY_KILLED,
    GAME_COMPLETED,
    SECRET_DISCOVERED,
    SPEED_RUN,

    ENTER_CROSSROADS,
    ENTER_GREENPATH,
    ENTERED_BOSS_ROOM,

    PLAYER_STARTED_WALKING,
    PLAYER_ENDED_WALKING,
    PLAYER_DASH,
    PLAYER_MONARCH_WINGS,
    PLAYER_STARTED_WALL_SLIDING,
    PLAYER_ENDED_WALL_SLIDING,

    PLAYER_FOCUS_START,
    PLAYER_FOCUS_END,
    PLAYER_SOUL_GAIN,

    PLAYER_ATTACKING,
    POGO_SPIKE,
    ATTACKING_WALL,
    WALL_DESTROYED,
    PLAYER_VENGEFUL,
    PLAYER_HOWLING,

    ENEMY_HURT,
    PLAYER_HURT,
    PLAYER_DOUBLE_HURT,
    PLAYER_DEATH,

    ZOTE_IS_TALKING,
    ZOTE_STARTED_ATTACKING,
    ZOTE_ENDED_ATTACKING,

    SLAM_MACE,
    BOSS_JUMP,
    BOSS_LAND,
    POWER_SLAM_MACE,
    BOSS_STUN,
    BOSS_BEGIN_RUNNING,
    BOSS_ENDED_RUNNING,

    SAVE_GAME;
}
