package com.Ap.HollowKnight.controller.events;

public enum GameEvent {
    BOSS_DEFEATED,
    ENEMY_KILLED,
    GAME_COMPLETED,
    SECRET_DISCOVERED,
    PLAYER_STARTED_WALKING,
    PLAYER_ENDED_WALKING,
    PLAYER_ATTACKING,
    POGO_SPIKE,
    ATTACKING_WALL,
    ZOTE_IS_TALKING,
    ZOTE_IS_ATTACKING,
    WALL_SLIDING_BEGIN,
    WALL_SLIDING_END,
    SLAM_MACE,
    ENEMY_HURT,
    PLAYER_HURT,
    PLAYER_DOUBLE_HURT,
    PLAYER_FOCUS,
    PLAYER_DASH,
    PLAYER_VENGEFUL,
    PLAYER_HOWLING,

}
